# values.yaml

replicaCount: 1

service:
  type: ClusterIP
  port: 5173
  targetPort: 80
  nodePort: ""

image:
  pullPolicy: IfNotPresent
  repository: zgsm/credit-manager
  tag: "v1.1.5"

containerPorts:
  web: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

rollingUpdate:
  maxUnavailable: "25%"
  maxSurge: "25%"

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - zgsm-admin-system
          topologyKey: "kubernetes.io/hostname"

nodeSelector: {}
# kubernetes.io/os: linux

nginxConfig: |
  server {
      listen 80;
      root /usr/share/nginx/html;

      index index.html index.htm;

      location /credit/manager/ {
          alias /usr/share/nginx/html/;
          try_files $uri /credit/manager/index.html;
      }


      location / {
          try_files $uri $uri/ /index.html;
      }

      error_page 500 502 503 504 /50x.html;
      location = /50x.html {
          root /usr/share/nginx/html;
      }
      server_tokens off;
      gzip on;
      gzip_vary on;
      gzip_proxied any;
      gzip_comp_level 6;
      gzip_buffers 16 8k;
      gzip_http_version 1.1;
      gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

      gzip_disable "MSIE [1-6]\.(?!.*SV1)";
  }